### ISSUE TITLE
Cannot import after installing from pip - find_packages error?

### ISSUE THREAD

**Issue by robintw** [msiemens/tinydb-serialization#1]
After the recent upgrade to TinyDB 3.0, I've tried to install this module so that my custom serializers still work. Unfortunately, after installing via `pip install tinydb-serialization` I cannot import the module:

```
~ python -c 'import tinydb_serialization'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'tinydb_serialization'
```

I think the reason behind this is that the module isn't actually being installed properly. Looking at the `setup.py` file, it uses `find_packages()` to list the packages that must be installed. In this case, the single source file (`tinydb_serialization.py`) is not a package, so isn't found by `find_packages()`.

I thought it was better to raise an issue rather than submit a PR, as there are multiple ways to fix this. Possibly the best way is to move the source file into a proper package, but that may require changes in the way that the module is imported.

I think my analysis is correct - apologies if not!

**Comment by msiemens** [comment]
Thanks for reporting & investigating this, @robintw! I've now moved `tinydb_serialization.py` to a proper package and released v1.0.1 where this should be fixed.

**Comment by dagraham** [comment]
Has this issue returned with 3.5.0?

**Comment by msiemens** [comment]
Do you mean Python 3.5.0 oder TinyDB 3.5.0?
