### ISSUE TITLE
Just ship DateTimeSerializer in the standard package

### ISSUE THREAD

**Issue by corydodt** [msiemens/tinydb-serialization#10]
This middleware is useful for lots of reasons, but it seems to me DateTimeSerializer is going to be one of the biggest reasons anyone ends up here.

Just ship it so people can use it directly instead of everyone recreating the example from your docs.

**Comment by msiemens** [comment]
Version 2.1.0 which was just released includes a `DateTimeSerializer` just as you requested 🙃

**Comment by corydodt** [comment]
Thank you!
