### ISSUE TITLE
[Documentation] Add admonishment RE: multiple serializers for multiple TinyDBs.

### ISSUE THREAD

**Issue by benetherington** [msiemens/tinydb-serialization#11]
Hey, folks! I can't believe how well documented and commented this library is. Excellent, excellent work!

I ran into a problem that might not be very common, so feel free to close this issue without action if the juice isn't worth the squeeze. I'm working with two different databases, and both utilize datetime serialization. My naive first try looked like:

```
serialization = SerializationMiddleware()
serialization.register_serializer(DateTimeSerializer(), 'TinyDate')
audience_db = TinyDB('audience.json', storage=serialization)
tweet_db = TinyDB('tweets.json', storage=serialization)
```

Without looking at the source code (or the Middleware documentation), I assumed that middleware objects took database references as arguments and could operate on multiple databases at will. Of course, this actually results in the tweet_db and audience_db operating on the same data. Instead, the following code is correct:

```
audience_serialization = SerializationMiddleware()
audience_serialization.register_serializer(DateTimeSerializer(), 'TinyDate')
audience_db = TinyDB('audience.json', storage=audience_serialization)

twitter_serialization = SerializationMiddleware()
twitter_serialization.register_serializer(DateTimeSerializer(), 'TinyDate')
tweet_db = TinyDB('tweets.json', storage=twitter_serialization)
```

Is this something that could/should be pointed out in the tinydb-serialization documentation?

Thanks!

**Comment by msiemens** [comment]
Hey @benetherington, thanks for reporting this! You're 100% correct, this behavior should be documented. I hope the readme makes this clear now :)

**Comment by benetherington** [comment]
That looks good to me! Thank you!
