### ISSUE TITLE
Add DateSerializer

### ISSUE THREAD

**Issue by nkantar** [msiemens/tinydb-serialization#16]
Hello!

I’m working on a project that needs a `DateSerializer`, which is really quite simple and similar to the existing `DateTimeSerializer`. Would you have an interest in merging a PR if I were to create one?

Thanks!

**Comment by msiemens** [comment]
Hey! Yes, this sounds useful and shouldn't be too complicated, I'd be glad to merge a PR 🙂

**Comment by adjoli** [comment]
Hy @msiemens and @nkantar. I'm eagerly awaiting this PR. I also need this Serializer in a project.

**Comment by msiemens** [comment]
Hey @adjoli, I've released this in v2.2.0 🙂
